# ─── КАТЕГОРИИ ───

SECTIONS = [
    {"id": "family", "title": "Family", "emoji": "👨‍👩‍👧", "level": "A1-A2"},
    {"id": "home", "title": "Home", "emoji": "🏠", "level": "A1-A2"},
    {"id": "routine", "title": "Daily Routine", "emoji": "⏰", "level": "A1-A2"},
    {"id": "food", "title": "Food", "emoji": "🍔", "level": "A1-A2"},
    {"id": "clothes", "title": "Clothes", "emoji": "👕", "level": "A1-A2"},
    {"id": "appearance", "title": "Appearance", "emoji": "👤", "level": "A1-A2"},
    {"id": "weather", "title": "Weather", "emoji": "☀️", "level": "A1-A2"},
    {"id": "transport", "title": "Transport", "emoji": "🚗", "level": "A1-A2"},
    {"id": "work", "title": "Work", "emoji": "💼", "level": "A1-A2"},
    {"id": "health", "title": "Health", "emoji": "💊", "level": "A1-A2"},
    {"id": "shopping", "title": "Shopping", "emoji": "🛒", "level": "A1-A2"},
    {"id": "holidays", "title": "Holidays", "emoji": "🏖️", "level": "A1-A2"},
    {"id": "feelings", "title": "Feelings", "emoji": "😊", "level": "B1"},
    {"id": "character", "title": "Character", "emoji": "🎭", "level": "B1"},
    {"id": "relationships", "title": "Relationships", "emoji": "💕", "level": "B1"},
    {"id": "communication", "title": "Communication", "emoji": "💬", "level": "B1"},
    {"id": "money", "title": "Money & Business", "emoji": "💰", "level": "B1"},
    {"id": "technology", "title": "Technology", "emoji": "💻", "level": "B1"},
    {"id": "education", "title": "Education", "emoji": "🎓", "level": "B1"},
    {"id": "media", "title": "Media", "emoji": "📰", "level": "B1"},
    {"id": "city", "title": "City & Town", "emoji": "🏙️", "level": "B1"},
    {"id": "nature", "title": "Nature", "emoji": "🌳", "level": "B1"},
    {"id": "time", "title": "Time", "emoji": "🕐", "level": "B1"},
    {"id": "housework", "title": "Housework", "emoji": "🧹", "level": "B1"},
    {"id": "business", "title": "Business & Negotiations", "emoji": "🤝", "level": "B2+"},
    {"id": "politics", "title": "Politics & Law", "emoji": "⚖️", "level": "B2+"},
    {"id": "environment", "title": "Environment", "emoji": "🌍", "level": "B2+"},
    {"id": "art", "title": "Art & Culture", "emoji": "🎨", "level": "B2+"},
    {"id": "science", "title": "Science", "emoji": "🔬", "level": "B2+"},
    {"id": "general", "title": "Общее", "emoji": "📦", "level": "general"},
]


def get_section(sid):
    return next((s for s in SECTIONS if s["id"] == sid), SECTIONS[-1])


# ─── ЦИТАТЫ ДНЯ ───

QUOTES = [
    {"text": "The limits of my language mean the limits of my world.", "author": "Ludwig Wittgenstein"},
    {"text": "Learning is a treasure that will follow its owner everywhere.", "author": "Chinese Proverb"},
    {"text": "The more that you read, the more things you will know.", "author": "Dr. Seuss"},
    {"text": "To have another language is to possess a second soul.", "author": "Charlemagne"},
    {"text": "Language is the road map of a culture.", "author": "Rita Mae Brown"},
    {"text": "A different language is a different vision of life.", "author": "Federico Fellini"},
    {"text": "The best way to predict the future is to invent it.", "author": "Alan Kay"},
    {"text": "Success is the sum of small efforts repeated day in and day out.", "author": "Robert Collier"},
    {"text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis"},
    {"text": "The secret of getting ahead is getting started.", "author": "Mark Twain"},
    {"text": "Education is the most powerful weapon which you can use to change the world.", "author": "Nelson Mandela"},
    {"text": "The journey of a thousand miles begins with a single step.", "author": "Lao Tzu"},
    {"text": "Knowledge is power.", "author": "Francis Bacon"},
    {"text": "Practice makes perfect.", "author": "English Proverb"},
    {"text": "Where there is a will, there is a way.", "author": "English Proverb"},
    {"text": "Every day is a chance to get better.", "author": "Unknown"},
    {"text": "Don't watch the clock; do what it does. Keep going.", "author": "Sam Levenson"},
    {"text": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt"},
    {"text": "A word a day keeps the ignorance away.", "author": "Unknown"},
]


# ─── НЕПРАВИЛЬНЫЕ ГЛАГОЛЫ ───

IRREGULAR_VERBS = [
    {"base": "be", "past": "was/were", "pp": "been", "rus": "быть"},
    {"base": "become", "past": "became", "pp": "become", "rus": "становиться"},
    {"base": "begin", "past": "began", "pp": "begun", "rus": "начинать"},
    {"base": "break", "past": "broke", "pp": "broken", "rus": "ломать"},
    {"base": "bring", "past": "brought", "pp": "brought", "rus": "приносить"},
    {"base": "build", "past": "built", "pp": "built", "rus": "строить"},
    {"base": "buy", "past": "bought", "pp": "bought", "rus": "покупать"},
    {"base": "catch", "past": "caught", "pp": "caught", "rus": "ловить"},
    {"base": "choose", "past": "chose", "pp": "chosen", "rus": "выбирать"},
    {"base": "come", "past": "came", "pp": "come", "rus": "приходить"},
    {"base": "cost", "past": "cost", "pp": "cost", "rus": "стоить"},
    {"base": "cut", "past": "cut", "pp": "cut", "rus": "резать"},
    {"base": "do", "past": "did", "pp": "done", "rus": "делать"},
    {"base": "draw", "past": "drew", "pp": "drawn", "rus": "рисовать"},
    {"base": "drink", "past": "drank", "pp": "drunk", "rus": "пить"},
    {"base": "drive", "past": "drove", "pp": "driven", "rus": "водить"},
    {"base": "eat", "past": "ate", "pp": "eaten", "rus": "есть"},
    {"base": "fall", "past": "fell", "pp": "fallen", "rus": "падать"},
    {"base": "feel", "past": "felt", "pp": "felt", "rus": "чувствовать"},
    {"base": "fight", "past": "fought", "pp": "fought", "rus": "бороться"},
    {"base": "find", "past": "found", "pp": "found", "rus": "находить"},
    {"base": "fly", "past": "flew", "pp": "flown", "rus": "летать"},
    {"base": "forget", "past": "forgot", "pp": "forgotten", "rus": "забывать"},
    {"base": "get", "past": "got", "pp": "got/gotten", "rus": "получать"},
    {"base": "give", "past": "gave", "pp": "given", "rus": "давать"},
    {"base": "go", "past": "went", "pp": "gone", "rus": "идти"},
    {"base": "grow", "past": "grew", "pp": "grown", "rus": "расти"},
    {"base": "have", "past": "had", "pp": "had", "rus": "иметь"},
    {"base": "hear", "past": "heard", "pp": "heard", "rus": "слышать"},
    {"base": "hold", "past": "held", "pp": "held", "rus": "держать"},
    {"base": "keep", "past": "kept", "pp": "kept", "rus": "хранить"},
    {"base": "know", "past": "knew", "pp": "known", "rus": "знать"},
    {"base": "leave", "past": "left", "pp": "left", "rus": "уходить"},
    {"base": "lose", "past": "lost", "pp": "lost", "rus": "терять"},
    {"base": "make", "past": "made", "pp": "made", "rus": "делать"},
    {"base": "meet", "past": "met", "pp": "met", "rus": "встречать"},
    {"base": "pay", "past": "paid", "pp": "paid", "rus": "платить"},
    {"base": "put", "past": "put", "pp": "put", "rus": "класть"},
    {"base": "read", "past": "read", "pp": "read", "rus": "читать"},
    {"base": "ride", "past": "rode", "pp": "ridden", "rus": "ехать"},
    {"base": "run", "past": "ran", "pp": "run", "rus": "бегать"},
    {"base": "say", "past": "said", "pp": "said", "rus": "говорить"},
    {"base": "see", "past": "saw", "pp": "seen", "rus": "видеть"},
    {"base": "sell", "past": "sold", "pp": "sold", "rus": "продавать"},
    {"base": "send", "past": "sent", "pp": "sent", "rus": "отправлять"},
    {"base": "sing", "past": "sang", "pp": "sung", "rus": "петь"},
    {"base": "sit", "past": "sat", "pp": "sat", "rus": "сидеть"},
    {"base": "sleep", "past": "slept", "pp": "slept", "rus": "спать"},
    {"base": "speak", "past": "spoke", "pp": "spoken", "rus": "говорить"},
    {"base": "spend", "past": "spent", "pp": "spent", "rus": "тратить"},
    {"base": "stand", "past": "stood", "pp": "stood", "rus": "стоять"},
    {"base": "swim", "past": "swam", "pp": "swum", "rus": "плавать"},
    {"base": "take", "past": "took", "pp": "taken", "rus": "брать"},
    {"base": "teach", "past": "taught", "pp": "taught", "rus": "учить"},
    {"base": "tell", "past": "told", "pp": "told", "rus": "рассказывать"},
    {"base": "think", "past": "thought", "pp": "thought", "rus": "думать"},
    {"base": "understand", "past": "understood", "pp": "understood", "rus": "понимать"},
    {"base": "wake", "past": "woke", "pp": "woken", "rus": "просыпаться"},
    {"base": "wear", "past": "wore", "pp": "worn", "rus": "носить"},
    {"base": "win", "past": "won", "pp": "won", "rus": "побеждать"},
    {"base": "write", "past": "wrote", "pp": "written", "rus": "писать"},
]


# ─── ФРАЗОВЫЕ ГЛАГОЛЫ ───

PHRASAL_VERBS = [
    {"phrase": "give up", "rus": "бросить", "example": "I gave up smoking."},
    {"phrase": "look after", "rus": "заботиться", "example": "She looks after her sister."},
    {"phrase": "run out of", "rus": "закончиться", "example": "We ran out of milk."},
    {"phrase": "find out", "rus": "выяснить", "example": "I found out the truth."},
    {"phrase": "come back", "rus": "вернуться", "example": "He came back home."},
    {"phrase": "go on", "rus": "продолжать", "example": "Go on, tell me!"},
    {"phrase": "turn off", "rus": "выключить", "example": "Turn off the light."},
    {"phrase": "turn on", "rus": "включить", "example": "Turn on the TV."},
    {"phrase": "put on", "rus": "надеть", "example": "Put on your coat."},
    {"phrase": "take off", "rus": "снять", "example": "Take off your shoes."},
    {"phrase": "wake up", "rus": "проснуться", "example": "I wake up at 7."},
    {"phrase": "get up", "rus": "встать", "example": "Get up, sleepyhead!"},
    {"phrase": "sit down", "rus": "сесть", "example": "Sit down, please."},
    {"phrase": "stand up", "rus": "встать", "example": "Stand up straight."},
    {"phrase": "come in", "rus": "войти", "example": "Come in!"},
    {"phrase": "go out", "rus": "выйти", "example": "We go out on Fridays."},
    {"phrase": "look for", "rus": "искать", "example": "I'm looking for my keys."},
    {"phrase": "look forward to", "rus": "ждать с нетерпением", "example": "I look forward to seeing you."},
    {"phrase": "give back", "rus": "вернуть", "example": "Give back my book."},
    {"phrase": "take care of", "rus": "заботиться", "example": "Take care of yourself."},
    {"phrase": "get along with", "rus": "ладить", "example": "I get along with my brother."},
    {"phrase": "break down", "rus": "сломаться", "example": "My car broke down."},
    {"phrase": "carry on", "rus": "продолжать", "example": "Carry on with your work."},
    {"phrase": "check out", "rus": "проверить", "example": "Check out this song."},
    {"phrase": "figure out", "rus": "разобраться", "example": "I figured out the puzzle."},
    {"phrase": "grow up", "rus": "вырасти", "example": "I grew up in Moscow."},
    {"phrase": "hang out", "rus": "тусоваться", "example": "Let's hang out tomorrow."},
    {"phrase": "hold on", "rus": "подождать", "example": "Hold on a second."},
    {"phrase": "keep on", "rus": "продолжать", "example": "Keep on trying."},
    {"phrase": "move on", "rus": "двигаться дальше", "example": "Let's move on."},
    {"phrase": "pick up", "rus": "подобрать", "example": "Pick up the phone."},
    {"phrase": "point out", "rus": "указать", "example": "He pointed out my mistake."},
    {"phrase": "put off", "rus": "отложить", "example": "Put off the meeting."},
    {"phrase": "set up", "rus": "установить", "example": "Set up the tent."},
    {"phrase": "show up", "rus": "появиться", "example": "He showed up late."},
    {"phrase": "take over", "rus": "взять контроль", "example": "She took over the project."},
    {"phrase": "throw away", "rus": "выбросить", "example": "Throw away the trash."},
    {"phrase": "try on", "rus": "примерить", "example": "Try on this dress."},
    {"phrase": "work out", "rus": "тренироваться", "example": "I work out every day."},
    {"phrase": "write down", "rus": "записать", "example": "Write down the address."},
]


# ─── ИДИОМЫ ───

IDIOMS = [
    {"idiom": "break a leg", "rus": "ни пуха, ни пера", "literal": "сломай ногу"},
    {"idiom": "piece of cake", "rus": "проще простого", "literal": "кусок торта"},
    {"idiom": "hit the books", "rus": "засесть за учёбу", "literal": "ударить книги"},
    {"idiom": "under the weather", "rus": "неважно себя чувствовать", "literal": "под погодой"},
    {"idiom": "once in a blue moon", "rus": "очень редко", "literal": "раз в голубую луну"},
    {"idiom": "spill the beans", "rus": "проболтаться", "literal": "пролить бобы"},
    {"idiom": "cost an arm and a leg", "rus": "стоить очень дорого", "literal": "стоить руку и ногу"},
    {"idiom": "let the cat out of the bag", "rus": "раскрыть секрет", "literal": "выпустить кота из мешка"},
    {"idiom": "kill two birds with one stone", "rus": "убить двух зайцев", "literal": "убить двух птиц одним камнем"},
    {"idiom": "the ball is in your court", "rus": "твой ход", "literal": "мяч на твоём корте"},
    {"idiom": "bite the bullet", "rus": "стиснуть зубы", "literal": "укусить пулю"},
    {"idiom": "break the ice", "rus": "растопить лёд", "literal": "сломать лёд"},
    {"idiom": "cut corners", "rus": "халтурить", "literal": "резать углы"},
    {"idiom": "hit the sack", "rus": "пойти спать", "literal": "ударить мешок"},
    {"idiom": "it's raining cats and dogs", "rus": "льёт как из ведра", "literal": "дождь из кошек и собак"},
    {"idiom": "let sleeping dogs lie", "rus": "не буди лихо", "literal": "дай спящим собакам лежать"},
    {"idiom": "miss the boat", "rus": "упустить шанс", "literal": "пропустить лодку"},
    {"idiom": "on cloud nine", "rus": "на седьмом небе", "literal": "на девятом облаке"},
    {"idiom": "pull yourself together", "rus": "возьми себя в руки", "literal": "собери себя вместе"},
    {"idiom": "see eye to eye", "rus": "сходиться во мнениях", "literal": "видеть глаз в глаз"},
    {"idiom": "sit on the fence", "rus": "занимать нейтралитет", "literal": "сидеть на заборе"},
    {"idiom": "take it easy", "rus": "не напрягайся", "literal": "принимай это легко"},
    {"idiom": "the last straw", "rus": "последняя капля", "literal": "последняя соломинка"},
    {"idiom": "time flies", "rus": "время летит", "literal": "время летает"},
    {"idiom": "under your nose", "rus": "прямо под носом", "literal": "под твоим носом"},
    {"idiom": "when pigs fly", "rus": "когда рак на горе свистнет", "literal": "когда свиньи полетят"},
    {"idiom": "you can't judge a book by its cover", "rus": "не суди по обложке", "literal": "нельзя судить книгу по обложке"},
    {"idiom": "actions speak louder than words", "rus": "дела говорят громче слов", "literal": "действия говорят громче слов"},
    {"idiom": "better late than never", "rus": "лучше поздно, чем никогда", "literal": "лучше поздно, чем никогда"},
    {"idiom": "easier said than done", "rus": "легко сказать, да трудно сделать", "literal": "легче сказать, чем сделать"},
]


# ─── ФИКСИРОВАННЫЕ ТОПИКИ ───

FIXED_TOPICS = [
    {"id": "my_day", "title": "My Day", "emoji": "☀️", "helper": ["wake up", "breakfast", "work", "evening", "sleep", "morning", "lunch", "dinner"]},
    {"id": "my_family", "title": "My Family", "emoji": "👨‍👩‍👧", "helper": ["mother", "father", "brother", "sister", "love", "home", "parents", "children"]},
    {"id": "my_hobbies", "title": "My Hobbies", "emoji": "🎮", "helper": ["play", "read", "music", "sport", "game", "draw", "sing", "dance"]},
    {"id": "my_city", "title": "My City", "emoji": "🏙️", "helper": ["street", "park", "shop", "museum", "beautiful", "big", "small", "center"]},
    {"id": "my_dreams", "title": "My Dreams", "emoji": "💭", "helper": ["want", "future", "travel", "family", "success", "dream", "hope", "believe"]},
    {"id": "my_job", "title": "My Job", "emoji": "💼", "helper": ["office", "boss", "meeting", "colleague", "task", "project", "career", "salary"]},
    {"id": "my_travels", "title": "My Travels", "emoji": "✈️", "helper": ["airport", "ticket", "hotel", "luggage", "passport", "flight", "beach", "tourist"]},
    {"id": "my_food", "title": "My Food", "emoji": "🍕", "helper": ["breakfast", "lunch", "dinner", "tasty", "cook", "restaurant", "hungry", "delicious"]},
    {"id": "my_health", "title": "My Health", "emoji": "💪", "helper": ["sport", "gym", "doctor", "healthy", "sleep", "water", "vitamins", "energy"]},
    {"id": "my_future", "title": "My Future", "emoji": "🚀", "helper": ["career", "family", "travel", "success", "dream", "plan", "goal", "achieve"]},
]
